name: Build OpenWrt

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev libssl-dev git

      - name: Download OpenWrt Source Code
        run: |
          git clone https://github.com/coolsnowwolf/lede.git openwrt
          cd openwrt

      - name: Generate .config
        run: |
          cd openwrt
          make menuconfig # 或者 make defconfig，取决于您是否需要交互式配置
          # 如果您有一个预定义的.config文件，可以在这里复制它
          # cp path/to/your/.config .config

      - name: Save .config
        run: |
          cd openwrt
          # 将.config文件推送到GitHub仓库，以便下次构建时使用
          git config --global user.name 'Your Name'
          git config --global user.email 'your.email@example.com'
          git add .config
          git commit -m 'Update .config'
          git push
